INSERT INTO public.food_bank_items (name, category) VALUES
  ('Canned black beans', 'Canned Goods'),
  ('Canned kidney beans', 'Canned Goods'),
  ('Canned chickpeas', 'Canned Goods'),
  ('Canned pinto beans', 'Canned Goods'),
  ('Canned diced tomatoes', 'Canned Goods'),
  ('Canned tomato sauce', 'Canned Goods'),
  ('Canned corn', 'Canned Goods'),
  ('Canned green beans', 'Canned Goods'),
  ('Canned peas', 'Canned Goods'),
  ('Canned mixed vegetables', 'Canned Goods'),
  ('Canned tuna', 'Canned Goods'),
  ('Canned chicken', 'Canned Goods'),
  ('Canned salmon', 'Canned Goods'),
  ('Canned fruit cocktail', 'Canned Goods'),
  ('Canned peaches', 'Canned Goods'),
  ('Canned pineapple', 'Canned Goods'),
  ('Applesauce', 'Canned Goods'),
  ('Canned pumpkin', 'Canned Goods'),
  ('Canned soup', 'Canned Goods'),
  ('Chicken broth', 'Canned Goods'),
  ('Spaghetti sauce', 'Canned Goods'),
  ('Salsa', 'Canned Goods'),
  ('White rice', 'Dry Goods'),
  ('Brown rice', 'Dry Goods'),
  ('Spaghetti', 'Dry Goods'),
  ('Macaroni', 'Dry Goods'),
  ('Egg noodles', 'Dry Goods'),
  ('Instant ramen noodles', 'Dry Goods'),
  ('Rolled oats', 'Dry Goods'),
  ('Cold cereal', 'Dry Goods'),
  ('Dry lentils', 'Dry Goods'),
  ('Dry black beans', 'Dry Goods'),
  ('Dry pinto beans', 'Dry Goods'),
  ('All-purpose flour', 'Dry Goods'),
  ('Cornmeal', 'Dry Goods'),
  ('White sugar', 'Dry Goods'),
  ('Cooking oil', 'Dry Goods'),
  ('Peanut butter', 'Dry Goods'),
  ('Jam or jelly', 'Dry Goods'),
  ('Crackers', 'Dry Goods'),
  ('Mac and cheese', 'Dry Goods'),
  ('Instant mashed potatoes', 'Dry Goods'),
  ('Coffee', 'Dry Goods'),
  ('Tea bags', 'Dry Goods'),
  ('Bottled water', 'Dry Goods'),
  ('Raisins', 'Dry Goods'),
  ('Potatoes', 'Produce'),
  ('Onions', 'Produce'),
  ('Carrots', 'Produce'),
  ('Apples', 'Produce'),
  ('Bananas', 'Produce'),
  ('Powdered milk', 'Dairy'),
  ('Shelf-stable milk', 'Dairy'),
  ('Cheese', 'Dairy'),
  ('Eggs', 'Dairy'),
  ('Ground beef', 'Protein'),
  ('Frozen chicken', 'Protein'),
  ('Bread', 'Other'),
  ('Tortillas', 'Other'),
  ('Mayonnaise', 'Other'),
  ('Mustard', 'Other'),
  ('Ketchup', 'Other')
ON CONFLICT (name) DO NOTHING;
